openapi: 3.0.1
info:
  title: OData Service for namespace microsoft.graph
  description: This OData service is located at http://localhost
  version: 1.0.1
servers:
  - url: http://localhost
paths:
  /notes:
    description: Provides operations to manage the collection of notes entities.
    get:
      tags:
        - notes.notes
      summary: Get entities from notes
      operationId: notes.notes.ListNotes
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - createdAt
                - createdAt desc
                - body
                - body desc
                - user
                - user desc
                - title
                - title desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - createdAt
                - body
                - user
                - title
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          $ref: '#/components/responses/microsoft.graph.notesCollectionResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      security:
        - Application:
            - Notes.ReadWrite.All
            - Notes.Delete.All
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - notes.notes
      summary: Add new entity to notes
      operationId: notes.notes.CreateNotes
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.notes'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.notes'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/notes/{notes-id}':
    description: Provides operations to manage the collection of notes entities.
    get:
      tags:
        - notes.notes
      summary: Get entity from notes by key
      operationId: notes.notes.GetNotes
      parameters:
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - createdAt
                - body
                - user
                - title
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.notes'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - notes.notes
      summary: Update entity in notes
      operationId: notes.notes.UpdateNotes
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.notes'
        required: true
      responses:
        '204':
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - notes.notes
      summary: Delete entity from notes
      operationId: notes.notes.DeleteNotes
      parameters:
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    parameters:
      - name: notes-id
        in: path
        description: 'key: id of notes'
        required: true
        schema:
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          type: string
          format: uuid
        x-ms-docs-key-type: notes
  /notes/$count:
    description: Provides operations to count the resources in the collection.
    get:
      summary: Get the number of the resource
      operationId: Get.Count.notes-e638
      responses:
        '200':
          $ref: '#/components/responses/ODataCountResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
  /:
    get:
      operationId: graphService.GetGraphService
      responses:
        '200':
          description: OK
          links:
            notes: { }
components:
  schemas:
    microsoft.graph.notes:
      title: notes
      type: object
      properties:
        id:
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          type: string
          format: uuid
        createdAt:
          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
          type: string
          format: date-time
        body:
          type: string
        user:
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          type: string
          format: uuid
        title:
          type: string
    microsoft.graph.user:
      title: user
      type: object
      properties:
        id:
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          type: string
          format: uuid
        notes:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.notes'
    microsoft.graph.ODataErrors.ODataError:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/microsoft.graph.ODataErrors.MainError'
    microsoft.graph.ODataErrors.MainError:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
          nullable: true
        details:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.ODataErrors.ErrorDetails'
        innererror:
          $ref: '#/components/schemas/microsoft.graph.ODataErrors.InnerError'
    microsoft.graph.ODataErrors.ErrorDetails:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
          nullable: true
    microsoft.graph.ODataErrors.InnerError:
      type: object
      description: The structure of this object is service-specific
    ODataCountResponse:
      type: integer
      format: int32
    microsoft.graph.notesCollectionResponse:
      title: Collection of notes
      type: object
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.notes'
        '@odata.nextLink':
          type: string
    StringCollectionResponse:
      title: Collection of string
      type: object
      properties:
        value:
          type: array
          items:
            type: string
        '@odata.nextLink':
          type: string
    ReferenceUpdateSchema:
      type: object
      properties:
        '@odata.id':
          type: string
        '@odata.type':
          type: string
          nullable: true
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/microsoft.graph.ODataErrors.ODataError'
    ODataCountResponse:
      description: The count of the resource
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/ODataCountResponse'
    microsoft.graph.notesCollectionResponse:
      description: Retrieved collection
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/microsoft.graph.notesCollectionResponse'
    StringCollectionResponse:
      description: Retrieved collection
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StringCollectionResponse'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
  examples:
    microsoft.graph.notes:
      value:
        body: String
        createdAt: '0001-01-01T00:00:00.0000000+00:00'
        id: 00000000-0000-0000-0000-000000000000 (identifier)
        title: String
        user: 00000000-0000-0000-0000-000000000000
    microsoft.graph.user:
      value:
        id: 00000000-0000-0000-0000-000000000000 (identifier)
        notes:
          - '@odata.type': microsoft.graph.notes
tags:
  - name: notes.notes
    x-ms-docs-toc-type: page